# Generated by Django 5.1.3 on 2024-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
