# Generated by Django 5.1.3 on 2024-12-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('website', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(default='Wellrock Tower', max_length=255)),
                ('street_num', models.CharField(default='1st Street', max_length=255)),
                ('district_num', models.CharField(default='1st District', max_length=255)),
                ('city_name', models.CharField(default='Quezon City', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agent_first_name', models.CharField(max_length=255)),
                ('agent_last_name', models.CharField(max_length=255)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.agent')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.building')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(default='General Room', max_length=255)),
                ('venue_type', models.CharField(default='Function Hall', max_length=255)),
                ('venue_floor_num', models.CharField(default='GF', max_length=2)),
                ('venue_floor_area', models.CharField(default='20 sqm', max_length=255)),
                ('venue_capacity', models.CharField(default='20 max', max_length=255)),
                ('renovation_status', models.CharField(default='No', max_length=5)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.building')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_participant_number', models.CharField(default='0 pax', max_length=255)),
                ('reservation_timeframe_start', models.DateTimeField()),
                ('reservation_timeframe_end', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usermanagement.customer')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(default='Chair', max_length=255)),
                ('amenity_category', models.CharField(default='Furniture', max_length=255)),
                ('amenity_description', models.CharField(default='A piece of furniture equipment', max_length=255)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='website.venue')),
            ],
        ),
    ]
