# Generated by Django 5.1.3 on 2024-12-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_agent_manager_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='venue_id',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='venue_id',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
