# Generated by Django 5.1.3 on 2024-12-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_building_id_agent_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='manager',
            new_name='agent',
        ),
    ]
