# Generated by Django 5.1.3 on 2024-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_manager_venue_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='amenity_quantity',
            field=models.CharField(default='1pc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
