# Generated by Django 5.1.3 on 2024-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_location',
            field=models.CharField(default='Manila', max_length=255),
            preserve_default=False,
        ),
    ]
